In [1]:
import planets
import heat1d

In [8]:
# Latitude
lat = 0.0

# Planet
p = planets.Moon

# Create model
m = heat1d.Model(p, lat*np.pi/180.0, 5)

# Run model
m.run()

In [6]:
m.profile.z

array([0.        , 0.00362112, 0.00796647, 0.01318088, 0.01943818,
       0.02694694, 0.03595745, 0.04677006, 0.0597452 , 0.07531536,
       0.09399955, 0.11642058, 0.14332582, 0.17561211, 0.21435565,
       0.2608479 , 0.3166386 , 0.38358745, 0.46392606, 0.56033239,
       0.67601999])

In [9]:
m.profile.z

array([0.        , 0.00362112, 0.00796647, 0.01318088, 0.01943818,
       0.02694694, 0.03595745, 0.04677006, 0.0597452 , 0.07531536,
       0.09399955, 0.11642058, 0.14332582, 0.17561211, 0.21435565,
       0.2608479 , 0.3166386 , 0.38358745, 0.46392606, 0.56033239,
       0.67601999])

In [7]:
m.profile.T

array([383.00969802, 371.63831213, 359.34124228, 346.03894944,
       331.70453253, 316.43504851, 300.55779417, 284.77410536,
       270.28229462, 258.71064469, 251.61949215, 249.59300808,
       251.61105086, 255.52750754, 259.30980954, 261.87912996,
       263.16844078, 263.73420839, 264.15946212, 264.59384401,
       264.87695541])

In [10]:
m.profile.T

array([383.00969802, 371.63831213, 359.34124228, 346.03894944,
       331.70453253, 316.43504851, 300.55779417, 284.77410536,
       270.28229462, 258.71064469, 251.61949215, 249.59300808,
       251.61105086, 255.52750754, 259.30980954, 261.87912996,
       263.16844078, 263.73420839, 264.15946212, 264.59384401,
       264.87695541])