In [1]:
# Standard libraries
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

import heat1d
import planets

# Planetary libraries
from heat1d import prettyPlots, plotting, main

prettyPlots.setStyle()

In [2]:
from heat1d.grids import NonUniformGrid

In [3]:
grid = NonUniformGrid(10)

In [4]:
from heat1d import Configurator

In [5]:
config = Configurator()
config

Configurator(sigma=5.6703744191844314e-08, S0=1361.0, chi=2.7, F=0.5, m=10, n=5, b=20, DTSURF=0.1, NYEARSEQ=1, NPERDAY=24, DTBOT=0.1)

In [6]:
# Latitude
lat = 0.0
# Planet
p = planets.Moon

# Create model
m = heat1d.Model(p, lat=lat * np.pi / 180.0, ndays=5, config=config)

In [7]:
p.H

0.07

In [8]:
m.run()

In [9]:
m.T[-1]

array([383.00969802, 371.63831213, 359.34124228, 346.03894944,
       331.70453253, 316.43504851, 300.55779417, 284.77410536,
       270.28229462, 258.71064469, 251.61949215, 249.59300808,
       251.61105086, 255.52750754, 259.30980954, 261.87912996,
       263.16844078, 263.73420839, 264.15946212, 264.59384401,
       264.87695541])

In [10]:
m.profile.cp

array([891.84926779, 878.55484808, 863.01021079, 844.81992827,
       823.61537964, 799.20408166, 771.8443165 , 742.67983993,
       714.21482755, 690.35600022, 675.25203064, 670.86942106,
       675.2338356 , 683.62084919, 691.61553786, 696.98693734,
       699.6641351 , 700.83506824, 701.71363649, 702.60968646,
       703.19294352])

In [12]:
m.profile.k

array([0.00335831, 0.00369953, 0.00402451, 0.00431876, 0.00456807,
       0.00476233, 0.00490078, 0.0049978 , 0.00508591, 0.00521146,
       0.00541963, 0.00573132, 0.00612293, 0.00652847, 0.00687223,
       0.0071089 , 0.00724048, 0.00730379, 0.00733912, 0.0073643 ,
       0.0073786 ])

In [8]:
%matplotlib widget

In [9]:
plt.figure()
plt.plot(m.Qs_values, ls='-')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [16]:
max(m.Qs_values)

1238.707362821832

In [17]:
max(ms.Qs_series)

1232.2142223884432

In [10]:
from spicer import MoonSpicer

In [11]:
ms = MoonSpicer()

In [12]:
ms.set_spoint_by(lat=0, lon=0)

In [13]:
len(m.r_values)

14111

In [14]:
fluxes, _ = ms.time_series('F_flat', 3074, 14111)

In [15]:
plt.plot(ms.Qs_series)

In [16]:
from astropy.visualization import quantity_support
quantity_support()

<astropy.visualization.units.quantity_support.<locals>.MplQuantityConverter at 0x7fb19b84ffd0>

In [25]:
ms.illum_angles.solar

<Quantity 0.81605235 rad>

In [21]:
plt.plot(fluxes)

In [29]:
plotting.diurnal_curves(m)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [32]:
m.t / 3600 / 24 / 30

4.921724115562111

In [5]:
from astropy.constants import au

In [6]:
au.value / 1e9

149.5978707

In [7]:
au.value

149597870700.0

In [8]:
au

<<class 'astropy.constants.iau2015.IAU2015'> name='Astronomical Unit' value=149597870700.0 uncertainty=0.0 unit='m' reference='IAU 2012 Resolution B2'>

In [11]:
pd.read_clipboard(header=None)

0      1         2         3        4   5         6
0   2016-Aug-25  00:00  0.000400  2.618153  89.0984  /L   90.8703
1   2016-Aug-25  00:10  0.000411  2.587498  88.2379  /L   91.7300
2   2016-Aug-25  00:20  0.000421  2.557823  87.4193  /L   92.5478
3   2016-Aug-25  00:30  0.000431  2.529084  86.6391  /L   93.3272
4   2016-Aug-25  00:40  0.000441  2.501239  85.8942  /L   94.0713
5   2016-Aug-25  00:50  0.000451  2.474247  85.1820  /L   94.7828
6   2016-Aug-25  01:00  0.000461  2.448067  84.5000  /L   95.4641
7   2016-Aug-25  01:10  0.000471  2.422661  83.8459  /L   96.1174
8   2016-Aug-25  01:20  0.000480  2.397995  83.2178  /L   96.7447
9   2016-Aug-25  01:30  0.000490  2.374032  82.6139  /L   97.3479
10  2016-Aug-25  01:40  0.000500  2.350742  82.0327  /L   97.9285
11  2016-Aug-25  01:50  0.000509  2.328093  81.4725  /L   98.4879
12  2016-Aug-25  02:00  0.000518  2.306057  80.9322  /L   99.0276
13  2016-Aug-25  02:10  0.000527  2.284605  80.4104  /L   99.5488
14  2016-Aug-25  02:20  0.000537  2.263713  79.9060  /L  100.0525
15  2016-Aug-25  02:30  0.000546  2.243355  79.4180  /L  100.5398
16  2016-Aug-25  02:40  0.000555  2.223510  78.9456  /L  101.0116
17  2016-Aug-25  02:50  0.000563  2.204154  78.4877  /L  101.4689
18  2016-Aug-25  03:00  0.000572  2.185267  78.0436  /L  101.9123
19  2016-Aug-25  03:10  0.000581  2.166830  77.6126  /L  102.3427
20  2016-Aug-25  03:20  0.000590  2.148824  77.1940  /L  102.7608
21  2016-Aug-25  03:30  0.000598  2.131233  76.7871  /L  103.1671
22  2016-Aug-25  03:40  0.000607  2.114039  76.3913  /L  103.5622
23  2016-Aug-25  03:50  0.000615  2.097228  76.0062  /L  103.9468
24  2016-Aug-25  04:00  0.000624  2.080783  75.6311  /L  104.3213
25  2016-Aug-25  04:10  0.000632  2.064691  75.2657  /L  104.6862

In [16]:
z = np.array([1, 4, 9, 17, 29])

In [17]:
z

array([ 1,  4,  9, 17, 29])

In [19]:
dz = np.diff(z)

In [20]:
d3z = dz[1:] * dz[0:-1] * (dz[1:] + dz[0:-1])

In [21]:
d3z.shape

(3,)

In [22]:
dz.shape

(4,)

In [31]:
main.T_eq(p, 0)

273.04634410887496

In [32]:
main.T_radeq(p, 0)

386.14584299516207

In [33]:
p.cpCoeff

[8.9093e-09, -1.234e-05, 0.0023616, 2.7431, -3.6125]

In [34]:
p.Qb

0.018

In [35]:
config

Configurator(sigma=5.6703744191844314e-08, S0=1361.0, chi=2.7, F=0.5, m=10, n=5, b=20, DTSURF=0.1, NYEARSEQ=1, NPERDAY=24, DTBOT=0.1)

In [36]:
p

This planet object contains information on Moon
Type "help(Planet)" for more information

In [37]:
type(p)

planets._planets.Planet

In [39]:
m.profile.cp

array([719.7666609, 719.7666609, 719.7666609, 719.7666609, 719.7666609,
       719.7666609, 719.7666609, 719.7666609, 719.7666609, 719.7666609,
       719.7666609, 719.7666609, 719.7666609, 719.7666609, 719.7666609,
       719.7666609, 719.7666609, 719.7666609, 719.7666609, 719.7666609,
       719.7666609])

In [41]:
m.T.shape

(4150, 21)

In [42]:
m.T[-1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.])